import Head from "next/head";
import { Container, Flex } from "@chakra-ui/react";
import { Navbar } from "@/components/Navbar";
import { Main } from "@/components/Main";
import { Footer } from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Capitalizator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="6xl">
        <Navbar />
        <Main />
        <Footer />
      </Container>
    </>
  );
}
